### ISSUE TITLE
Include LICENSE in the source distribution

### ISSUE THREAD

**Issue by jenzopr** [rasbt/mputil#1]
Dear Sebastian!

I wondered if it is possible to include the LICENSE file in the source package that is available on Pypi. Background is that I wanted to add `mputil` to conda-forge in order to reference it easily in conda envs. Unfortunately, the recipe fails during linting, because of the license file.

As far as I see it, adding a `MANIFEST.in` file or

```
data_files = [("", ["LICENSE"])]
```

to the setup() call in setup.py should do the trick.
Please let me know what you think. I could also open a PR if that helps.

Furthermore, I wanted to thank you for this clever package! I recently implemented it (together with input streaming) in a time-crucial application which used to run 6hrs and is now down to 90 mins!! 

Best,
Jens

**Comment by rasbt** [comment]
Hi Jens,

glad to hear that the package has been useful to you! And of course, I'd be happy to add the license file -- I wasn't aware that it was missing from PyPI, thanks for the note!

**Comment by rasbt** [comment]
Should be fixed now

**Comment by jenzopr** [comment]
Great! I'll test again and PR to conda-forge then 👍 Thanks a lot!

**Comment by jenzopr** [comment]
Available: https://github.com/conda-forge/mputil-feedstock 🎉

**Comment by rasbt** [comment]
Awesome, thanks for doing that! I will add a note to the repo.
